# Generated by Django 4.2.5 on 2024-04-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_activation_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
    ]
