apiVersion: v1
kind: Pod
metadata:
  name: user-account-pod
  labels:
    app: user-account
spec:
  containers:
    - name: user-account-container
      image: laum07/user-account-microservice:latest
      ports:
        - containerPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: user-account-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: user-account
